import React, {useState} from 'react'
import { Switch } from '@headlessui/react';

const PasswordAndSecurity = () => {

  const [enabled, setEnabled] = useState(false);

  return (
    <div className='divide-y divide-[#474747]'>
      {/* password */}
      <form className='w-full'>
        <div className='p-[28px] md:p-14 space-y-8'>
          <h2 className='text-white text-xl font-bold'>Authentication options</h2>

          <div className='space-y-4'>
            <h3 className='text-white text-2xl font-bold'>Password</h3>
            <p className='text-white text-sm md:text-base'>Secure your account by adding a password</p>

            <div className='flex flex-col md:flex-row items-center gap-4'>
              <input
                type='password'
                placeholder='Password'
                className='w-full xl:w-auto bg-white text-sm lg:text-base placeholder:text-gray-400 px-3 py-2 rounded-lg focus:outline-none border-2 border-transparent focus:border-[#9359d5] mt-1'
              />
              <input
                type='password'
                placeholder='Confirm Password'
                className='w-full xl:w-auto bg-white text-sm lg:text-base placeholder:text-gray-400 px-3 py-2 rounded-lg focus:outline-none border-2 border-transparent focus:border-[#9359d5] mt-1'
              />
            </div>
          </div>

          {/* cancel and save button */}
          <div className='flex items-center space-x-4'>
            {/* cancel */}
            <div className='bg-gradient-to-r from-cyan-400 to-violet-500 rounded-lg p-0.5'>
              <button className='text-white text-sm md:text-sm font-semibold bg-[#171717] px-10 py-3 rounded-lg hover:scale-105 transition-all ease-in-out duration-200'>Cancel</button>
            </div>

            {/* save */}
            <button type='submit' className='text-white text-sm md:text-sm font-semibold bg-gradient-to-r from-cyan-400 to-violet-500 px-10 py-3 rounded-lg hover:scale-105 transition-all ease-in-out duration-200'>Save</button>
          </div>
        </div>
      </form>
      {/* two step verification */}
      <form className='w-full'>
        <div>
          <div className='p-[28px] md:p-14'>
            <h2 className='text-white text-2xl font-bold'>Two-step verification options</h2>
            <p className='text-white text-sm md:text-base'>Add an extra layer of security to block unauthorized access and protect your account.</p>
          </div>

          <div className='divide-y divide-[#474747]'>
            {/* Authenticator app code */}
            <div className='flex items-center p-[28px] md:px-14 md:py-10'>
              <div className='flex-1'>
                <h3 className='text-white text-xl font-bold'>Authenticator app code</h3>
                <p className='text-white text-sm md:text-base'>Enter a code generated by your authenticator app to confirm it’s you.</p>
              </div>
              <div>
                <Switch
                  checked={enabled}
                  onChange={setEnabled}
                  className={`${enabled ? 'bg-[#201E7B]' : 'bg-[#222354]'}
                                                        relative inline-flex items-center w-16 h-8 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus-visible:ring-2  focus-visible:ring-white focus-visible:ring-opacity-75`}
                >
                  <span className="sr-only">Use setting</span>
                  <div
                    aria-hidden="true"
                    className={`${enabled ? 'translate-x-full' : 'translate-x-0'}
                                                            pointer-events-none inline-block w-1/2 aspect-square transform rounded-full bg-transparent shadow-lg ring-0 transition duration-200 ease-in-out p-0.5`}
                  >
                    <div className='w-full h-full bg-white rounded-full'></div>
                  </div>
                </Switch>
              </div>
            </div>

            {/* Mobile app prompt */}
            <div className='flex items-center p-[28px] md:px-14 md:py-10'>
              <div className='flex-1'>
                <h3 className='text-white text-xl font-bold'>Mobile app prompt</h3>
                <p className='text-white text-sm md:text-base'>Receive a prompt from your mobile app to confirm it’s you.</p>
              </div>
              <div>
                <Switch
                  checked={enabled}
                  onChange={setEnabled}
                  className={`${enabled ? 'bg-[#201E7B]' : 'bg-[#222354]'}
                                                        relative inline-flex items-center w-16 h-8 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus-visible:ring-2  focus-visible:ring-white focus-visible:ring-opacity-75`}
                >
                  <span className="sr-only">Use setting</span>
                  <div
                    aria-hidden="true"
                    className={`${enabled ? 'translate-x-full' : 'translate-x-0'}
                                                            pointer-events-none inline-block w-1/2 aspect-square transform rounded-full bg-transparent shadow-lg ring-0 transition duration-200 ease-in-out p-0.5`}
                  >
                    <div className='w-full h-full bg-white rounded-full'></div>
                  </div>
                </Switch>
              </div>
            </div>

            {/* Text message */}
            <div className='flex items-center p-[28px] md:px-14 md:py-10'>
              <div className='flex-1'>
                <h3 className='text-white text-xl font-bold'>Text message</h3>
                <p className='text-white text-sm md:text-base'>Receive a six digit code by text message to confirm it’s you.</p>
              </div>
              <div>
                <Switch
                  checked={enabled}
                  onChange={setEnabled}
                  className={`${enabled ? 'bg-[#201E7B]' : 'bg-[#222354]'}
                                                        relative inline-flex items-center w-16 h-8 shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out focus:outline-none focus-visible:ring-2  focus-visible:ring-white focus-visible:ring-opacity-75`}
                >
                  <span className="sr-only">Use setting</span>
                  <div
                    aria-hidden="true"
                    className={`${enabled ? 'translate-x-full' : 'translate-x-0'}
                                                            pointer-events-none inline-block w-1/2 aspect-square transform rounded-full bg-transparent shadow-lg ring-0 transition duration-200 ease-in-out p-0.5`}
                  >
                    <div className='w-full h-full bg-white rounded-full'></div>
                  </div>
                </Switch>
              </div>
            </div>

            {/* security question */}
            <div className='p-[28px] md:px-14 md:py-10 space-y-6'>
              <h3 className='text-white text-xl font-bold'>Security question</h3>
              <p className='text-white text-sm md:text-base'>Answer a question you choose to confirm it’s you.</p>
              {/* question */}
              <div className='space-y-2'>
                <label className='text-white text-sm lg:text-base font-medium'>Add a question</label>
                <div>
                  <select className='w-full md:w-4/5 lg:w-1/2 bg-white text-sm lg:text-base placeholder:text-gray-400 px-3 py-2 rounded-lg focus:outline-none border-2 border-transparent focus:border-[#9359d5] mt-1'>
                    <option value="">Select a question</option>
                    {
                      [...Array(50)].map((index) => (
                        <option key={index} value="question">question here</option>
                      ))
                    }
                  </select>
                </div>
              </div>
              {/* answer */}
              <div className='space-y-2'>
                <label className='text-white text-sm lg:text-base font-medium'>Answer</label>
                <div>
                  <input
                    type='text'
                    className='w-full md:w-4/5 lg:w-1/2 bg-white text-sm lg:text-base placeholder:text-gray-400 px-3 py-2 rounded-lg focus:outline-none border-2 border-transparent focus:border-[#9359d5]'
                  />
                </div>
              </div>
              {/* checkboxes */}
              <div className='space-y-2'>
                {/* checkbox 1 */}
                <div className='flex !items-start space-x-2'>
                  <div>
                    <input
                      type='checkbox'
                      className='lg:w-5 lg:h-5'
                    />
                  </div>
                  <p className='text-white text-sm lg:text-base'>I understand my account will be locked if I am unable to answer this question</p>
                </div>
                {/* checkbox 2 */}
                <div className='flex !items-start space-x-2'>
                  <div>
                    <input
                      type='checkbox'
                      className='lg:w-5 lg:h-5'
                    />
                  </div>
                  <p className='text-white text-sm lg:text-base'>Keep me logged in on this device</p>
                </div>
              </div>
            </div>
          </div>

          {/* cancel and save button */}
          <div className='flex items-center space-x-4 p-[28px] md:px-14 md:py-10'>
            {/* cancel */}
            <div className='bg-gradient-to-r from-cyan-400 to-violet-500 rounded-lg p-0.5'>
              <button className='text-white text-sm md:text-sm font-semibold bg-[#171717] px-10 py-3 rounded-lg hover:scale-105 transition-all ease-in-out duration-200'>Cancel</button>
            </div>

            {/* save */}
            <button type='submit' className='text-white text-sm md:text-sm font-semibold bg-gradient-to-r from-cyan-400 to-violet-500 px-10 py-3 rounded-lg hover:scale-105 transition-all ease-in-out duration-200'>Save</button>
          </div>
        </div>
      </form>
    </div>
  )
}

export default PasswordAndSecurity